# Generated by Django 5.0.3 on 2024-03-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminstrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_district',
        ),
    ]
