# Generated by Django 5.0.3 on 2024-03-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminstrator', '0002_tbl_category_delete_tbl_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_AdminRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdminRegistration_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Dstrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District_name', models.CharField(max_length=50)),
            ],
        ),
    ]
