# Generated by Django 5.0.3 on 2024-03-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminstrator', '0003_tbl_adminregistration_tbl_dstrict'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_name', models.CharField(max_length=50)),
            ],
        ),
    ]
