# Generated by Django 5.0.3 on 2024-03-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminstrator', '0004_tbl_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password_name', models.CharField(max_length=50)),
            ],
        ),
    ]
