# Generated by Django 5.0.3 on 2024-03-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminstrator', '0005_tbl_admin_tbl_contact_tbl_email_tbl_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fees_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_name', models.CharField(max_length=50)),
            ],
        ),
    ]
