# Generated by Django 5.0.3 on 2024-03-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminstrator', '0006_tbl_course_tbl_duration_tbl_fees_tbl_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_Dstrict',
        ),
    ]
