# Generated by Django 5.0.3 on 2024-03-12 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminstrator', '0007_tbl_district_delete_tbl_dstrict'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Admin',
        ),
        migrations.DeleteModel(
            name='tbl_AdminRegistration',
        ),
        migrations.DeleteModel(
            name='tbl_Contact',
        ),
        migrations.DeleteModel(
            name='tbl_Course',
        ),
        migrations.DeleteModel(
            name='tbl_Department',
        ),
        migrations.DeleteModel(
            name='tbl_Duration',
        ),
        migrations.DeleteModel(
            name='tbl_Email',
        ),
        migrations.DeleteModel(
            name='tbl_Fees',
        ),
        migrations.DeleteModel(
            name='tbl_Name',
        ),
        migrations.DeleteModel(
            name='tbl_Password',
        ),
    ]
