# Generated by Django 5.0.3 on 2024-03-13 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminstrator', '0010_tbl_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_district',
            old_name='District_name',
            new_name='district_name',
        ),
        migrations.CreateModel(
            name='tbl_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminstrator.tbl_district')),
            ],
        ),
    ]
