# Generated by Django 5.0.3 on 2024-03-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminstrator', '0011_rename_district_name_tbl_district_district_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(max_length=50)),
            ],
        ),
    ]
