# Generated by Django 5.0.3 on 2024-03-14 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminstrator', '0014_tbl_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_employee',
        ),
    ]
