# Generated by Django 5.0.3 on 2024-03-15 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminstrator', '0017_tbl_shopregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_shopregistration',
        ),
    ]
