# Generated by Django 5.0.3 on 2024-03-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminstrator', '0022_tbl_shopregistration_shop_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_shopregistration',
        ),
    ]
