# Generated by Django 5.0.3 on 2024-03-22 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminstrator', '0024_tbl_ewaste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_ewaste',
        ),
    ]
