# Generated by Django 5.0.3 on 2024-04-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminstrator', '0029_delete_tbl_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
