# Generated by Django 5.0.3 on 2024-04-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminstrator', '0030_tbl_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Course',
        ),
        migrations.RemoveField(
            model_name='tbl_employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='tbl_employee',
            name='designation',
        ),
        migrations.DeleteModel(
            name='tbl_department',
        ),
        migrations.DeleteModel(
            name='tbl_designation',
        ),
        migrations.DeleteModel(
            name='tbl_employee',
        ),
    ]
