# Generated by Django 5.0.3 on 2024-04-05 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adminstrator', '0026_tbl_ewaste'),
        ('Company', '0004_delete_tbl_waste'),
        ('User', '0005_alter_tbl_request_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_quantity', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminstrator.tbl_category')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_request')),
            ],
        ),
    ]
