# Generated by Django 5.0.3 on 2024-03-21 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminstrator', '0023_delete_tbl_shopregistration'),
        ('Guest', '0008_tbl_shopregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmp_name', models.CharField(max_length=50)),
                ('cmp_contact', models.CharField(max_length=50)),
                ('cmp_email', models.CharField(max_length=50)),
                ('cmp_password', models.CharField(max_length=50)),
                ('cmp_photo', models.FileField(upload_to='Assets/cmpPhoto/')),
                ('cmp_proof', models.FileField(upload_to='Assets/cmpProof/')),
                ('cmp_status', models.IntegerField(default='0')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminstrator.tbl_place')),
            ],
        ),
    ]
