# Generated by Django 5.0.3 on 2024-04-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_tbl_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_shopregistration',
        ),
    ]
