# Generated by Django 5.0.3 on 2024-04-05 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_tbl_company'),
        ('User', '0005_alter_tbl_request_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=100)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('complaint_details', models.CharField(max_length=1000)),
                ('complaint_staus', models.IntegerField(default='0')),
                ('complaint_reply', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
