# Generated by Django 5.0.3 on 2024-04-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_tbl_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_title', models.CharField(max_length=100)),
                ('feedback_date', models.DateField(auto_now_add=True)),
                ('feedback_details', models.CharField(max_length=1000)),
            ],
        ),
    ]
