# Generated by Django 5.0.3 on 2024-04-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_tbl_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_photo', models.FileField(upload_to='Assets/ImagePhoto/')),
            ],
        ),
    ]
